DEFAULT_FIELDS_PER_TABLE: dict[str, list[str]] = {
    "incident": [
        "sys_id",
        "number",
        "short_description",
        "description",
        "state",
        "priority",
        "urgency",
        "impact",
        "severity",
        "category",
        "subcategory",
        "caller_id",
        "opened_by",
        "assignment_group",
        "assigned_to",
        "sys_created_on",
        "sys_updated_on",
        "sys_updated_by",
    ],
    "sys_user_group": [
        "sys_id",
        "name",
        "active",
        "description",
        "email",
        "manager",
        "sys_created_on",
        "sys_updated_on",
        "sys_updated_by",
    ],
    "sc_catalog": [
        "sys_id",
        "title",
        "description",
        "active",
        "sys_scope",
        "sys_created_on",
        "sys_updated_on",
        "sys_updated_by",
    ],
}
