CLOUD_COSTS = {
	"code": 200,
	"status": "success",
	"data": [{
		"cluster-one/docker-desktop/argocd/argocd-application-controller-0/argocd-application-controller": {
			"name": "cluster-one/docker-desktop/argocd/argocd-application-controller-0/argocd-application-controller",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "argocd-application-controller",
				"controller": "argocd-application-controller",
				"controllerKind": "statefulset",
				"namespace": "argocd",
				"pod": "argocd-application-controller-0",
				"services": [
					"argocd-metrics"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-application-controller",
					"controller_revision_hash": "argocd-application-controller-bd8d4bf87",
					"kubernetes_io_metadata_name": "argocd",
					"statefulset_kubernetes_io_pod_name": "argocd-application-controller-0"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-applicationset-controller-6968db6485-vpn4v/argocd-applicationset-controller": {
			"name": "cluster-one/docker-desktop/argocd/argocd-applicationset-controller-6968db6485-vpn4v/argocd-applicationset-controller",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "argocd-applicationset-controller",
				"controller": "argocd-applicationset-controller",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-applicationset-controller-6968db6485-vpn4v",
				"services": [
					"argocd-applicationset-controller"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-applicationset-controller",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "6968db6485"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-dex-server-5776dcc845-vdfvb/dex": {
			"name": "cluster-one/docker-desktop/argocd/argocd-dex-server-5776dcc845-vdfvb/dex",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "dex",
				"controller": "argocd-dex-server",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-dex-server-5776dcc845-vdfvb",
				"services": [
					"argocd-dex-server"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-dex-server",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "5776dcc845"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-notifications-controller-5987567b6d-s8655/argocd-notifications-controller": {
			"name": "cluster-one/docker-desktop/argocd/argocd-notifications-controller-5987567b6d-s8655/argocd-notifications-controller",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "argocd-notifications-controller",
				"controller": "argocd-notifications-controller",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-notifications-controller-5987567b6d-s8655",
				"services": [
					"argocd-notifications-controller-metrics"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-notifications-controller",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "5987567b6d"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-redis-685866888c-b2kl9/redis": {
			"name": "cluster-one/docker-desktop/argocd/argocd-redis-685866888c-b2kl9/redis",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "redis",
				"controller": "argocd-redis",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-redis-685866888c-b2kl9",
				"services": [
					"argocd-redis"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-redis",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "685866888c"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-repo-server-786dc96dfb-mqf5g/argocd-repo-server": {
			"name": "cluster-one/docker-desktop/argocd/argocd-repo-server-786dc96dfb-mqf5g/argocd-repo-server",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "argocd-repo-server",
				"controller": "argocd-repo-server",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-repo-server-786dc96dfb-mqf5g",
				"services": [
					"argocd-repo-server"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-repo-server",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "786dc96dfb"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/argocd-server-5fcbb87749-rr7qp/argocd-server": {
			"name": "cluster-one/docker-desktop/argocd/argocd-server-5fcbb87749-rr7qp/argocd-server",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "argocd-server",
				"controller": "argocd-server",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "argocd-server-5fcbb87749-rr7qp",
				"services": [
					"argocd-server-metrics",
					"argocd-server"
				],
				"labels": {
					"app_kubernetes_io_name": "argocd-server",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "5fcbb87749"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-6hhwv/nginx": {
			"name": "cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-6hhwv/nginx",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "nginx",
				"controller": "nginx-deployment",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "nginx-deployment-7fb96c846b-6hhwv",
				"services": [
					"nginx-service"
				],
				"labels": {
					"app": "nginx",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "7fb96c846b"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-b87np/nginx": {
			"name": "cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-b87np/nginx",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "nginx",
				"controller": "nginx-deployment",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "nginx-deployment-7fb96c846b-b87np",
				"services": [
					"nginx-service"
				],
				"labels": {
					"app": "nginx",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "7fb96c846b"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-kd7vv/nginx": {
			"name": "cluster-one/docker-desktop/argocd/nginx-deployment-7fb96c846b-kd7vv/nginx",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "nginx",
				"controller": "nginx-deployment",
				"controllerKind": "deployment",
				"namespace": "argocd",
				"pod": "nginx-deployment-7fb96c846b-kd7vv",
				"services": [
					"nginx-service"
				],
				"labels": {
					"app": "nginx",
					"kubernetes_io_metadata_name": "argocd",
					"pod_template_hash": "7fb96c846b"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "argocd"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/default/guestbook-ui-b848d5d9d-74w95/guestbook-ui": {
			"name": "cluster-one/docker-desktop/default/guestbook-ui-b848d5d9d-74w95/guestbook-ui",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "guestbook-ui",
				"controller": "guestbook-ui",
				"controllerKind": "deployment",
				"namespace": "default",
				"pod": "guestbook-ui-b848d5d9d-74w95",
				"services": [
					"guestbook-ui"
				],
				"labels": {
					"app": "guestbook-ui",
					"kubernetes_io_metadata_name": "default",
					"pod_template_hash": "b848d5d9d"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "default"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/coredns-95db45d46-2m57b/coredns": {
			"name": "cluster-one/docker-desktop/kube-system/coredns-95db45d46-2m57b/coredns",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "coredns",
				"controller": "coredns",
				"controllerKind": "deployment",
				"namespace": "kube-system",
				"pod": "coredns-95db45d46-2m57b",
				"services": [
					"kube-dns"
				],
				"labels": {
					"k8s_app": "kube-dns",
					"kubernetes_io_metadata_name": "kube-system",
					"pod_template_hash": "95db45d46"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.1,
			"cpuCoreRequestAverage": 0.1,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.075,
			"cpuCost": 0.00237,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 73400320,
			"ramByteRequestAverage": 73400320,
			"ramByteUsageAverage": 0,
			"ramByteHours": 55050240,
			"ramCost": 0.00022,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00259,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/coredns-95db45d46-kpcth/coredns": {
			"name": "cluster-one/docker-desktop/kube-system/coredns-95db45d46-kpcth/coredns",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "coredns",
				"controller": "coredns",
				"controllerKind": "deployment",
				"namespace": "kube-system",
				"pod": "coredns-95db45d46-kpcth",
				"services": [
					"kube-dns"
				],
				"labels": {
					"k8s_app": "kube-dns",
					"kubernetes_io_metadata_name": "kube-system",
					"pod_template_hash": "95db45d46"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.1,
			"cpuCoreRequestAverage": 0.1,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.075,
			"cpuCost": 0.00237,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 73400320,
			"ramByteRequestAverage": 73400320,
			"ramByteUsageAverage": 0,
			"ramByteHours": 55050240,
			"ramCost": 0.00022,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00259,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/etcd-docker-desktop/etcd": {
			"name": "cluster-one/docker-desktop/kube-system/etcd-docker-desktop/etcd",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "etcd",
				"namespace": "kube-system",
				"pod": "etcd-docker-desktop",
				"labels": {
					"component": "etcd",
					"kubernetes_io_metadata_name": "kube-system",
					"tier": "control-plane"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.1,
			"cpuCoreRequestAverage": 0.1,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.075,
			"cpuCost": 0.00237,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 104857600,
			"ramByteRequestAverage": 104857600,
			"ramByteUsageAverage": 0,
			"ramByteHours": 78643200,
			"ramCost": 0.00031,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00268,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/kube-apiserver-docker-desktop/kube-apiserver": {
			"name": "cluster-one/docker-desktop/kube-system/kube-apiserver-docker-desktop/kube-apiserver",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "kube-apiserver",
				"namespace": "kube-system",
				"pod": "kube-apiserver-docker-desktop",
				"labels": {
					"component": "kube-apiserver",
					"kubernetes_io_metadata_name": "kube-system",
					"tier": "control-plane"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.25,
			"cpuCoreRequestAverage": 0.25,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.1875,
			"cpuCost": 0.00593,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00593,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/kube-controller-manager-docker-desktop/kube-controller-manager": {
			"name": "cluster-one/docker-desktop/kube-system/kube-controller-manager-docker-desktop/kube-controller-manager",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "kube-controller-manager",
				"namespace": "kube-system",
				"pod": "kube-controller-manager-docker-desktop",
				"labels": {
					"component": "kube-controller-manager",
					"kubernetes_io_metadata_name": "kube-system",
					"tier": "control-plane"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.2,
			"cpuCoreRequestAverage": 0.2,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.15,
			"cpuCost": 0.00474,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00474,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/kube-proxy-v299h/kube-proxy": {
			"name": "cluster-one/docker-desktop/kube-system/kube-proxy-v299h/kube-proxy",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "kube-proxy",
				"controller": "kube-proxy",
				"controllerKind": "daemonset",
				"namespace": "kube-system",
				"pod": "kube-proxy-v299h",
				"labels": {
					"controller_revision_hash": "746b7c5c88",
					"k8s_app": "kube-proxy",
					"kubernetes_io_metadata_name": "kube-system",
					"pod_template_generation": "1"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/kube-scheduler-docker-desktop/kube-scheduler": {
			"name": "cluster-one/docker-desktop/kube-system/kube-scheduler-docker-desktop/kube-scheduler",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "kube-scheduler",
				"namespace": "kube-system",
				"pod": "kube-scheduler-docker-desktop",
				"labels": {
					"component": "kube-scheduler",
					"kubernetes_io_metadata_name": "kube-system",
					"tier": "control-plane"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.1,
			"cpuCoreRequestAverage": 0.1,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.075,
			"cpuCost": 0.00237,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00237,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/storage-provisioner/storage-provisioner": {
			"name": "cluster-one/docker-desktop/kube-system/storage-provisioner/storage-provisioner",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "storage-provisioner",
				"namespace": "kube-system",
				"pod": "storage-provisioner",
				"labels": {
					"component": "storage-provisioner",
					"kubernetes_io_metadata_name": "kube-system"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T17:00:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 40,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/kube-system/vpnkit-controller/vpnkit-controller": {
			"name": "cluster-one/docker-desktop/kube-system/vpnkit-controller/vpnkit-controller",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "vpnkit-controller",
				"namespace": "kube-system",
				"pod": "vpnkit-controller",
				"labels": {
					"component": "vpnkit-controller",
					"kubernetes_io_metadata_name": "kube-system"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "kube-system"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/opencost/opencost-756774ccc9-79kbj/opencost": {
			"name": "cluster-one/docker-desktop/opencost/opencost-756774ccc9-79kbj/opencost",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "opencost",
				"controller": "opencost",
				"controllerKind": "deployment",
				"namespace": "opencost",
				"pod": "opencost-756774ccc9-79kbj",
				"services": [
					"opencost"
				],
				"labels": {
					"app": "opencost",
					"kubernetes_io_metadata_name": "opencost",
					"pod_template_hash": "756774ccc9"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "opencost"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.01,
			"cpuCoreRequestAverage": 0.01,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.0075,
			"cpuCost": 0.00024,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 55000000,
			"ramByteRequestAverage": 55000000,
			"ramByteUsageAverage": 0,
			"ramByteHours": 41250000,
			"ramCost": 0.00016,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.0004,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/opencost/opencost-756774ccc9-79kbj/opencost-ui": {
			"name": "cluster-one/docker-desktop/opencost/opencost-756774ccc9-79kbj/opencost-ui",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "opencost-ui",
				"controller": "opencost",
				"controllerKind": "deployment",
				"namespace": "opencost",
				"pod": "opencost-756774ccc9-79kbj",
				"services": [
					"opencost"
				],
				"labels": {
					"app": "opencost",
					"kubernetes_io_metadata_name": "opencost",
					"pod_template_hash": "756774ccc9"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "opencost"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0.01,
			"cpuCoreRequestAverage": 0.01,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0.0075,
			"cpuCost": 0.00024,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 55000000,
			"ramByteRequestAverage": 55000000,
			"ramByteUsageAverage": 0,
			"ramByteHours": 41250000,
			"ramCost": 0.00016,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.0004,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/prometheus/my-prometheus-kube-state-metrics-5788b6fc9c-hn6q2/kube-state-metrics": {
			"name": "cluster-one/docker-desktop/prometheus/my-prometheus-kube-state-metrics-5788b6fc9c-hn6q2/kube-state-metrics",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "kube-state-metrics",
				"controller": "my-prometheus-kube-state-metrics",
				"controllerKind": "deployment",
				"namespace": "prometheus",
				"pod": "my-prometheus-kube-state-metrics-5788b6fc9c-hn6q2",
				"services": [
					"my-prometheus-kube-state-metrics"
				],
				"labels": {
					"app_kubernetes_io_component": "metrics",
					"app_kubernetes_io_instance": "my-prometheus",
					"app_kubernetes_io_managed_by": "Helm",
					"app_kubernetes_io_name": "kube-state-metrics",
					"app_kubernetes_io_part_of": "kube-state-metrics",
					"app_kubernetes_io_version": "2.10.0",
					"helm_sh_chart": "kube-state-metrics-5.13.0",
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus",
					"pod_template_hash": "5788b6fc9c"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 0,
			"pvByteHours": 0,
			"pvCost": 0,
			"pvs": "null",
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/prometheus/my-prometheus-server-7dcbc9cc7f-79xxv/prometheus-server": {
			"name": "cluster-one/docker-desktop/prometheus/my-prometheus-server-7dcbc9cc7f-79xxv/prometheus-server",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "prometheus-server",
				"controller": "my-prometheus-server",
				"controllerKind": "deployment",
				"namespace": "prometheus",
				"pod": "my-prometheus-server-7dcbc9cc7f-79xxv",
				"services": [
					"my-prometheus-server"
				],
				"labels": {
					"app_kubernetes_io_component": "server",
					"app_kubernetes_io_instance": "my-prometheus",
					"app_kubernetes_io_managed_by": "Helm",
					"app_kubernetes_io_name": "prometheus",
					"app_kubernetes_io_part_of": "prometheus",
					"app_kubernetes_io_version": "v2.47.0",
					"helm_sh_chart": "prometheus-25.0.0",
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus",
					"pod_template_hash": "7dcbc9cc7f"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 4294967296,
			"pvByteHours": 3221225472,
			"pvCost": 0.00016,
			"pvs": {
				"cluster=cluster-one:name=pvc-3e4fb9a8-bda7-43e6-a705-241b86cff977": {
					"byteHours": 3221225472,
					"cost": 0.00016438356
				}
			},
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00016,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		},
		"cluster-one/docker-desktop/prometheus/my-prometheus-server-7dcbc9cc7f-79xxv/prometheus-server-configmap-reload": {
			"name": "cluster-one/docker-desktop/prometheus/my-prometheus-server-7dcbc9cc7f-79xxv/prometheus-server-configmap-reload",
			"properties": {
				"cluster": "cluster-one",
				"node": "docker-desktop",
				"container": "prometheus-server-configmap-reload",
				"controller": "my-prometheus-server",
				"controllerKind": "deployment",
				"namespace": "prometheus",
				"pod": "my-prometheus-server-7dcbc9cc7f-79xxv",
				"services": [
					"my-prometheus-server"
				],
				"labels": {
					"app_kubernetes_io_component": "server",
					"app_kubernetes_io_instance": "my-prometheus",
					"app_kubernetes_io_managed_by": "Helm",
					"app_kubernetes_io_name": "prometheus",
					"app_kubernetes_io_part_of": "prometheus",
					"app_kubernetes_io_version": "v2.47.0",
					"helm_sh_chart": "prometheus-25.0.0",
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus",
					"pod_template_hash": "7dcbc9cc7f"
				},
				"namespaceLabels": {
					"kubernetes_io_metadata_name": "prometheus",
					"name": "prometheus"
				}
			},
			"window": {
				"start": "2023-09-29T16:43:32Z",
				"end": "2023-09-29T17:43:32Z"
			},
			"start": "2023-09-29T16:55:00Z",
			"end": "2023-09-29T17:40:00Z",
			"minutes": 45,
			"cpuCores": 0,
			"cpuCoreRequestAverage": 0,
			"cpuCoreUsageAverage": 0,
			"cpuCoreHours": 0,
			"cpuCost": 0,
			"cpuCostAdjustment": 0,
			"cpuEfficiency": 0,
			"gpuCount": 0,
			"gpuHours": 0,
			"gpuCost": 0,
			"gpuCostAdjustment": 0,
			"networkTransferBytes": 0,
			"networkReceiveBytes": 0,
			"networkCost": 0,
			"networkCrossZoneCost": 0,
			"networkCrossRegionCost": 0,
			"networkInternetCost": 0,
			"networkCostAdjustment": 0,
			"loadBalancerCost": 0,
			"loadBalancerCostAdjustment": 0,
			"pvBytes": 4294967296,
			"pvByteHours": 3221225472,
			"pvCost": 0.00016,
			"pvs": {
				"cluster=cluster-one:name=pvc-3e4fb9a8-bda7-43e6-a705-241b86cff977": {
					"byteHours": 3221225472,
					"cost": 0.00016438356
				}
			},
			"pvCostAdjustment": 0,
			"ramBytes": 0,
			"ramByteRequestAverage": 0,
			"ramByteUsageAverage": 0,
			"ramByteHours": 0,
			"ramCost": 0,
			"ramCostAdjustment": 0,
			"ramEfficiency": 0,
			"externalCost": 0,
			"sharedCost": 0,
			"totalCost": 0.00016,
			"totalEfficiency": 0,
			"lbAllocations": "null"
		}
	}]
}