deleteDependentEntities: true
createMissingRelatedEntities: true
enableMergeEntity: true
resources:
  - kind: subscription
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | gsub(" ";"_")
          title: .name
          blueprint: '"azureSubscription"'
          properties:
            tags: .tags
            type: .type
            location: .location
  - kind: azureResourceContainer
    selector:
      query: 'true'
      graphQuery: >-
        "
        resourcecontainers
        | where type != 'microsoft.resources/subscriptions'
        | project id, type, name, location, tags, subscriptionId, resourceGroup
        | extend resourceGroup=tolower(resourceGroup)
        | extend type=tolower(type)
        "
    port:
      entity:
        mappings:
          identifier: .id | gsub(" ";"_")
          title: .name
          blueprint: '"azureResourceContainer"'
          properties:
            tags: .tags
            type: .type
            location: .location
  - kind: azureResource
    selector:
      query: 'true'
      graphQuery: >-
        "
        resources
        | project id, type, name, location, tags, subscriptionId, resourceGroup
        | extend resourceGroup=tolower(resourceGroup)
        | extend type=tolower(type)
        | join kind=leftouter (
            resourcecontainers
            | where type =~ 'microsoft.resources/subscriptions/resourcegroups'
            | project rgName=tolower(name), rgTags=tags, rgSubscriptionId=subscriptionId
        ) on $left.subscriptionId == $right.rgSubscriptionId and $left.resourceGroup == $right.rgName
        | project id, type, name, location, tags, subscriptionId, resourceGroup, rgTags
        "
    port:
      entity:
        mappings:
          identifier: .id | gsub(" ";"_")
          title: .name
          blueprint: '"azureResource"'
          properties:
            tags: .tags
            location: .location
          relations:
            subscription: ("/subscriptions/" + .subscriptionId) | gsub(" ";"_")
