deleteDependentEntities: true
createMissingRelatedEntities: true
enableMergeEntity: true
resources:
  - kind: subscription
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .subscriptionId
          title: .displayName
          blueprint: '"azureSubscription"'
          properties:
            tags: .tags
            state: .state
            subscriptionPolicy: .subscriptionPolicy
  - kind: resourceContainer
    selector:
      query: 'true'
      graphQuery: >-
        "
        resourcecontainers
        | where type =~ 'microsoft.resources/subscriptions/resourcegroups'
        | project id, type, name, location, tags, subscriptionId, resourceGroup
        | extend resourceGroup=tolower(resourceGroup)
        | extend type=tolower(type)
        "
    port:
      entity:
        mappings:
          identifier: .id | gsub(" ";"_")
          title: .name
          blueprint: '"azureResourceGroup"'
          properties:
            tags: .tags
            type: .type
            location: .location
          relations:
            subscription: ("/subscriptions/" + .subscriptionId) | gsub(" ";"_")
  - kind: resource
    selector:
      query: 'true'
      graphQuery: >-
        "
        resources
        | project id, type, name, location, tags, subscriptionId, resourceGroup
        | extend resourceGroup=tolower(resourceGroup)
        | extend type=tolower(type)
        | join kind=leftouter (
            resourcecontainers
            | where type =~ 'microsoft.resources/subscriptions/resourcegroups'
            | project rgName=tolower(name), rgTags=tags, rgSubscriptionId=subscriptionId
        ) on $left.subscriptionId == $right.rgSubscriptionId and $left.resourceGroup == $right.rgName
        | project id, type, name, location, tags, subscriptionId, resourceGroup, rgTags
        "
    port:
      entity:
        mappings:
          identifier: .id | gsub(" ";"_")
          title: .name
          blueprint: '"azureResource"'
          properties:
            tags: .tags
            location: .location
          relations:
            resource_group: >-
              ("/subscriptions/" + .subscriptionId + "/resourceGroups/"  + .resourceGroup) | gsub(" ";"_")
