extends: default

yaml-files:
  - '**/*.yaml'
  - '**/*.yml'
  - '**/*.json'

ignore: |
  **/node_modules/**
  .git/**
  .gitignore
  .yamlignore
  **/{{cookiecutter.integration_slug}}/**
  **/.mypy_cache/**
  **/.venv*/**
  docs/**
  deployment/**

rules:
  # ignore line length
  line-length: disable

  # ignore truthy checks
  truthy: disable

  # ignore document start marker
  document-start: disable
