createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizProject"'
          identifier: .id
          title: .name
          properties:
            archived: .archived
            businessUnit: .businessUnit
            description: .description
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizIssue"'
          identifier: .id
          title: .entitySnapshot.name + " | " + .entitySnapshot.type
          properties:
            # https://integrate.wiz.io/reference/issues-query#:~:text=Direct%20a%20user%20to%20an%20Issue%20in%20Wiz
            url: .id as $id | "https://app.wiz.io/issues#~(issue~'" + $id + ")"
            status: .status
            severity: .severity
            vulnerabilityType: .type
            notes: .notes
            wizIssueID: .entitySnapshot.id
            cloudResourceType: .entitySnapshot.type
            resourceName: .entitySnapshot.name
            cloudPlatform: .entitySnapshot.cloudPlatform
            linkToResource: if .entitySnapshot.cloudProviderURL == "" then null else .entitySnapshot.cloudProviderURL end
            cloudResourceID: .entitySnapshot.providerId
            cloudRegion: .entitySnapshot.region
            resourceGroupExternalId: .entitySnapshot.resourceGroupExternalId
            subscriptionExternalId: .entitySnapshot.subscriptionExternalId
            subscriptionName: .entitySnapshot.subscriptionName
            subscriptionTags: .entitySnapshot.subscriptionTags
            resourceTags: .entitySnapshot.tags
            vulnerability: .entitySnapshot
            createdAt: .createdAt
            updatedAt: .updatedAt
            statusChangedAt: .statusChangedAt
            resolvedAt: .resolvedAt
          relations:
            projects: .projects | map(.id)
            serviceTickets: .serviceTickets[].externalId
            control: .sourceRule.id
  - kind: control
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizControl"'
          identifier: .id
          title: .name
          properties:
            controlDescription: .controlDescription
            resolutionRecommendation: .resolutionRecommendation
  - kind: serviceTicket
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizServiceTicket"'
          identifier: .externalId
          title: .name
          properties:
            url: .url
  - kind: vulnerability-finding
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizVulnerabilityFinding"'
          identifier: .id
          title: .name
          properties:
            status: .status
            severity: .severity
            categories: .categories
            version: .version
            score: .score
            description: .description
            remediation: .remediation
            detectionMethod: .detectionMethod
            environments: .environments
            link: .link
            portalUrl: .portalUrl
            origin: .origin
            vulnerabilityExternalId: .vulnerabilityExternalId
            CVEDescription: .CVEDescription
            detailedName: .detailedName
            artifactMetadata: .artifactType
            hasFix: .hasFix
            hasExploit: .hasExploit
            isHighProfileThreat: .isHighProfileThreat
            updatedAt: .updatedAt
            resolvedAt: .resolvedAt
            firstDetectedAt: .firstDetectedAt
            publishedDate: .publishedDate
            rootComponent: .rootComponent
            applicationServices: .applicationServices
          relations:
            projects: .projects | map(.id)
  - kind: vulnerability-finding
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .detailedName + "-" + .version  | gsub("[^\\p{L}0-9@_.+:\\/=-]"; "")
          title: .detailedName + "-" + .version  | gsub("[^\\p{L}0-9@_.+:\\/=-]"; "")
          blueprint: '"sbomPackage"'
          properties:
            version: .version
            package: .detailedName
            manager: >-
              .artifactType.osPackageManager //
              .artifactType.codeLibraryLanguage
  - kind: technology
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizTechnology"'
          identifier: .id
          title: .name
          properties:
            description: .description
            categories: .categories | map(.name)
            usage: .usage
            status: .status
            risk: .risk
            note: .note
            ownerName: .ownerName
            businessModel: .businessModel
            popularity: .popularity
            projectCount: .projectCount
            codeRepoCount: .codeRepoCount
            isCloudService: .isCloudService
            supportedOperatingSystems: .supportedOperatingSystems
  - kind: hosted-technology
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizHostedTechnology"'
          identifier: .id
          title: .name
          properties:
            detectionMethods: .detectionMethods
            installedPackages: .installedPackages
            firstSeen: .firstSeen
            updatedAt: .updatedAt
            cpe: .cpe
          relations:
            technology: .technology.id
  - kind: repository
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"wizRepository"'
          identifier: .id
          title: .name
          properties:
            url: .url
            platform: .platform
            public: .public
            archived: .archived
            visibility: .visibility
            organization: .organization.id
            branches: .branches | map(.id)
          relations:
            projects: .projects | map(.id)
