deleteDependentEntities: true
createMissingRelatedEntities: True
resources:
  - kind: amplication_template
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"AmplicationTemplate"'
          properties:
            description: .description
            project: .project.name
            project_id: .project.id
            blueprint: .blueprint.name
            blueprint_id: .blueprint.id
  - kind: amplication_resource
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"AmplicationResource"'
          properties:
            description: .description
            project: .project.name
            project_id: .project.id
            blueprint: .blueprint.name
            blueprint_id: .blueprint.id
            git_organization: .gitRepository.gitOrganization.provider
            git_repository: '.gitRepository.gitOrganization.name + "/" + .gitRepository.name'
          relations:
            template: if .serviceTemplate != null then .serviceTemplate.id else null end
  - kind: amplication_alert
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: 'if .block != null then .type + ": " + .block.displayName else .type end'
          blueprint: '"AmplicationAlert"'
          properties:
            block_id: if .block != null then .block.id else null end
            block_displayName: if .block != null then .block.displayName else null end
            type: .type
            outdatedVersion: .outdatedVersion
            latestVersion: .latestVersion
            status: .status
          relations:
            resource: .resourceId
