resources:
  - kind: repository
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: ".uuid[1:-1]"
          title: .name
          blueprint: '"bitbucketRepository"'
          properties:
            url: .links.html.href
            scm: .scm
            language: .language
            description: .description
          relations:
            project: .project.key
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"bitbucketProject"'
          properties:
            url: .links.html.href
  - kind: pull-request
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .title
          blueprint: '"bitbucketPullRequest"'
          properties:
            state: .state
            author: .author.display_name
          relations:
            repository: .source.repository.uuid[1:-1]
  - kind: component
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"bitbucketComponent"'
          properties:
            description: .description
            createdOn: .created_on
          relations:
            repository: .repository.uuid[1:-1]            

