resources:
  - kind: AWS::S3::Bucket
    selector:
      query: 'true'
      includeActions:
        - GetBucketTaggingAction
        - GetBucketLocationAction
        - ListBucketsAction
    port:
      entity:
        mappings:
          identifier: .Properties.Arn
          title: .Properties.BucketName
          blueprint: '"s3Bucket"'
          properties:
            arn: .Properties.Arn
            region: .Properties.LocationConstraint
            creationDate: .Properties.CreationDate
            publicAccessBlockConfiguration: .Properties.PublicAccessBlockConfiguration
            tags: .Properties.Tags
