bitbucket:
  access_token: "ATBB6YJNMk6WXaygDtKhdrfdXThQC8FC7851"
  workspace: "oceanintegration"

port:
  api_key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdJZCI6Im9yZ19hZnpRcFVHdVpzZnFHcWNTIiwiaXNzIjoiaHR0cHM6Ly9hcGkuZ2V0cG9ydC5pbyIsImlzTWFjaGluZSI6dHJ1ZSwic3ViIjoidm9FalNuVkNwZU5jbzQzVW1SYlFqdnhYRXd3TzVkdEQiLCJwb3J0X3VzZXJfaWQiOiJ2b0VqU25WQ3BlTmNvNDNVbVJiUWp2eFhFd3dPNWR0RCIsImp0aSI6IjI1MGU3YzM1LWQzZjctNDlhYS05MjcxLTNjZWM0YzkwYmIzZCIsImlhdCI6MTczOTk0MzEyOSwiZXhwIjoxNzM5OTUzOTI5fQ.L6c5CDdGKDHhmT7Fh-gliS5DmlaskiUpuUAq40cTr3Y"
