createMissingRelatedEntities: true
resources:
  - kind: repository
    selector:
      query: "true"
      orgs:
        - "github"
      repoType: "all"
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: ".name"
          blueprint: '"githubRepository"'
          properties:
            name: .name
            description: .description
            url: .url
          relations:
            githubTeams: "[.teams[].id | tostring]"
  - kind: pull-requests
    selector:
      query: "true"
      orgs:
        - "github"
        - "melodyogonna"
      state: "all" # all, closed, open
      repoType: "public" # private, public
    port:
      entity:
        mappings:
          identifier: ".head.repo.name + (.id|tostring)"
          title: ".title"
          blueprint: '"githubPullRequest"'
          properties:
            creator: ".user.login"
            assignees: "[.assignees[].login]"
            reviewers: "[.requested_reviewers[].login]"
            status: ".status" # merged, closed, opened
            closedAt: ".closed_at"
            updatedAt: ".updated_at"
            mergedAt: ".merged_at"
            createdAt: ".created_at"
            link: ".html_url"
          relations:
            repository: .head.repo.name
  - kind: issues
    selector:
      query: ".pull_request == null"
      orgs:
        - github
      state: "open"
      repo_type: "public"
    port:
      entity:
        mappings:
          identifier: ".repository.name + (.id|tostring)"
          title: ".title"
          blueprint: '"githubIssues"'
          properties:
            creator: ".user.login"
            assignees: "[.assignees[].login]"
            labels: "[.labels[].nam]"
            status: ".state" # merged, closed, opened
            closedAt: ".closed_at"
            updatedAt: ".updated_at"
            createdAt: ".created_at"
            description: ".body"
            link: ".html_url"
          relations:
            repository: .repo
  - kind: teams
    selector:
      query: "true" # JQ boolean query. If evaluated to false - skip syncing the object.
      orgs:
        - github
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: .name
          blueprint: '"githubTeam"'
          properties:
            name: .name
            slug: .slug
            description: .description
            link: .html_url
            permission: .permission
  - kind: workflows
    selector:
      query: "true" # JQ boolean query. If evaluated to false - skip syncing the object.
      orgs:
        - github
      repo_type: "all"
    port:
      entity:
        mappings:
          identifier: ".repo + (.id|tostring)"
          title: ".name"
          blueprint: '"githubWorkflow"'
          properties:
            path: ".path"
            status: ".state"
            createdAt: ".created_at"
            updatedAt: ".updated_at"
            link: ".html_url"
          relations:
            repository: ".repo"
