"""Harbor webhook event types and constants."""

ARTIFACT_UPSERT_EVENTS = [
    "PUSH_ARTIFACT",
    "PULL_ARTIFACT",
    "SCANNING_COMPLETED",
]

ARTIFACT_DELETE_EVENTS = [
    "DELETE_ARTIFACT",
]

ARTIFACT_EVENTS = ARTIFACT_UPSERT_EVENTS + ARTIFACT_DELETE_EVENTS


REPOSITORY_UPSERT_EVENTS = [
    "PUSH_ARTIFACT",
    "PULL_ARTIFACT",
]

REPOSITORY_DELETE_EVENTS = [
    "DELETE_ARTIFACT",
]

REPOSITORY_EVENTS = REPOSITORY_UPSERT_EVENTS + REPOSITORY_DELETE_EVENTS

PROJECT_UPSERT_EVENTS = [
    "PUSH_ARTIFACT",
    "PULL_ARTIFACT",
    "DELETE_ARTIFACT",
    "QUOTA_EXCEED",
    "QUOTA_WARNING",
]

PROJECT_DELETE_EVENTS: list[str] = []

PROJECT_EVENTS = PROJECT_UPSERT_EVENTS + PROJECT_DELETE_EVENTS

ALL_HARBOR_EVENTS = [
    "PUSH_ARTIFACT",
    "PULL_ARTIFACT",
    "DELETE_ARTIFACT",
    "SCANNING_COMPLETED",
    "SCANNING_FAILED",
    "QUOTA_EXCEED",
    "QUOTA_WARNING",
    "REPLICATION",
    "TAG_RETENTION",
]

WEBHOOK_CREATE_EVENTS = [
    "PUSH_ARTIFACT",
    "PULL_ARTIFACT",
    "DELETE_ARTIFACT",
    "SCANNING_COMPLETED",
    "SCANNING_FAILED",
    "QUOTA_EXCEED",
    "QUOTA_WARNING",
    "REPLICATION",
    "TAG_RETENTION",
]
