createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".name"
          blueprint: '"githubRepository"'
          properties:
            htmlUrl: ".html_url"
            fullName: ".full_name"
            private: ".private"
            visibility: ".visibility"
            defaultBranch: ".default_branch"
            size: ".size"
            archived: ".archived"
            createdAt: ".created_at"
            updatedAt: ".updated_at"

  - kind: pull-request
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".title"
          blueprint: '"githubPullRequest"'
          properties:
            url: .html_url
            state: .state
            repo: .name
            author: .login
            number: .number
            createdAt: .created_at
            updatedAt: .updated_at
            base: .ref
            head: .ref
            merged: .merged
            draft: .draft
          relations:
            repository: .repo_name

  - kind: issue
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".title"
          blueprint: '"githubIssue"'
          properties:
            url: ".html_url // .url"
            state: .state
            repo: .name
            number: .number
            author: .login
            labels: .labels
            createdAt: .created_at
            updatedAt: .updated_at
            body: .body
          relations:
            repository: .repo_name

  - kind: team
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".name"
          blueprint: '"githubTeam"'
          properties:
            url: .url
            description: .description
            privacy: .privacy
            organization: .login
            createdAt: .created_at
            updatedAt: .updated_at
            permission: .permission
          relations:
            members: "if .__members != null then .__members | map(.id) else [] end"

  - kind: workflow
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".name"
          blueprint: '"githubWorkflow"'
          properties:
            url: ".workflow_url"
            runUrl: ".url"
            status: .status
            conclusion: .conclusion
            headBranch: .head_branch
            headSha: .head_sha
            runNumber: .run_number
            event: .event
            createdAt: .created_at
            updatedAt: .updated_at
            runStartedAt: .run_started_at
          relations:
            repository: .repo_name
