deleteDependentEntities: true
createMissingRelatedEntities: true
resources:
  - kind: repository
    selector:
      query: 'true'
      includeLanguages: 'true'
    port:
      entity:
        mappings:
          identifier: .full_name | gsub(" "; "")
          title: .name
          blueprint: '"githubRepository"'
          properties:
            readme: file://README.md
            url: .html_url
            defaultBranch: .default_branch
            language: .__languages | to_entries | max_by(.value) | .key
  - kind: member
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .login
          title: .name
          blueprint: '"githubMember"'
          properties:
            url: .html_url
            email: .email
  - kind: team-with-members
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .slug
          title: .name
          blueprint: '"githubTeam"'
          properties:
            url: .html_url
            description: .description
          relations:
            githubMembers: .__members | select(. != null) | map(.login)
  - kind: pull-request
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"githubPullRequest"'
          properties:
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .html_url
            leadTimeHours: >-
              (.created_at as $createdAt |
              if .merged_at == null then null else
                .merged_at as $mergedAt |
                ($createdAt | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) as $createdTimestamp |
                ($mergedAt | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) as $mergedTimestamp |
                (($mergedTimestamp - $createdTimestamp) / 3600) end)
            reviewers: .requested_reviewers | map(.login)
          relations:
            repository: .repository.full_name
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"githubIssue"'
          properties:
            creator: .user.login
            assignees: "[.assignees[].login]" # Will return an empty array if no assignees
            labels: "[.labels[].name]"
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            closedAt: .closed_at
            comments: .comments
            description: .body
            issueNumber: .number
            link: .html_url
          relations:
            repository: .repository.full_name
  - kind: workflow
    selector:
      query: "true" # JQ boolean query. If evaluated to false - skip syncing the object.
    port:
      entity:
        mappings:
          identifier: ".repo + (.id|tostring)"
          title: ".name"
          blueprint: '"githubWorkflow"'
          properties:
            path: ".path"
            status: ".state"
            createdAt: ".created_at"
            updatedAt: ".updated_at"
            link: ".html_url"
          relations:
            repository: ".repo"
