MAX_CONCURRENT_REQUESTS = 5
PAGE_SIZE = 100
CLIENT_TIMEOUT = 30
EVENT_TYPES = [
    "PUSH_ARTIFACT",
    "DELETE_ARTIFACT",
    "PULL_ARTIFACT",
    "SCANNING_COMPLETED",
    "SCANNING_FAILED",
]
LISTENER_EVENT_TYPES = []
