"""This module defines Harbor webhook event type constants"""

PUSH_ARTIFACT = "PUSH_ARTIFACT"
DELETE_ARTIFACT = "DELETE_ARTIFACT"
PULL_ARTIFACT = "PULL_ARTIFACT"

SCANNING_COMPLETED = "SCANNING_COMPLETED"
SCANNING_FAILED = "SCANNING_FAILED"

QUOTA_EXCEED = "QUOTA_EXCEED"
QUOTA_WARNING = "QUOTA_WARNING"

UPLOAD_CHART = "UPLOAD_CHART"
DOWNLOAD_CHART = "DOWNLOAD_CHART"
DELETE_CHART = "DELETE_CHART"

REPLICATION = "REPLICATION"

ARTIFACT_EVENTS = {
    PUSH_ARTIFACT,
    DELETE_ARTIFACT,
    SCANNING_COMPLETED,
    SCANNING_FAILED,
}

REPOSITORY_EVENTS = {
    PUSH_ARTIFACT,
    DELETE_ARTIFACT,
}

CHART_EVENTS = {
    UPLOAD_CHART,
    DOWNLOAD_CHART,
    DELETE_CHART,
}
