title: Argo CD
description: Argo CD integration for Port Ocean
icon: Argo
docs: https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/argocd/
features:
  - type: exporter
    section: Kubernetes Stack
    resources:
      - kind: cluster
      - kind: project
      - kind: application
      - kind: deployment-history
      - kind: kubernetes-resource
      - kind: managed-resource
saas:
  enabled: false
configurations:
  - name: token
    required: true
    description: ArgoCD API token. To create an API token, see the <a href="https://argoproj.github.io/argo-cd/getting_started/#4-create-an-api-access-token" target="_blank">ArgoCD documentation</a>.
    type: string
    sensitive: true
  - name: serverUrl
    type: string
    required: true
    description: The URL of the ArgoCD server. For example, https://argocd.example.com. Found in the URL field of your browser when you launch your ArgoCD instance
  - name: ignoreServerError
    type: boolean
    required: false
    description: Whether to ignore server errors when fetching data from ArgoCD. If set to true, the exporter will continue to fetch data and ingest entities in Port without failing the resync event even if the ArgoCD server returns an error. If set to false, the exporter will stop fetching data and fail the resync event when the ArgoCD server returns an error. Default is false.
    default: false
  - name: allowInsecure
    type: boolean
    required: false
    description: Whether to allow insecure connections to the ArgoCD server. If set to true, the exporter will allow insecure connections to the ArgoCD server. If set to false, the exporter will only allow secure connections to the ArgoCD server. Default is false.
    default: false
