type: argocd
description: Argocd integration for Port Ocean
icon: Argo
docs: https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/kubernetes/argocd
features:
  - type: exporter
    section: Kubernetes Stack
    resources:
      - kind: cluster
      - kind: project
      - kind: application
      - kind: deployment-history
      - kind: kubernetes-resource
configurations:
  - name: token
    required: true
    type: string
    sensitive: true
  - name: serverUrl
    type: string
    required: true
