createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"launchDarklyProject"'
          properties:
            tags: .tags
  - kind: segment
    selector:
      query: 'true'
      tags: null
      archived: null
      include_inactive: true
      name_pattern: null
      description_pattern: null
      has_rules: null
      has_included_users: null
      has_excluded_users: null
      environment_key: null
    port:
      entity:
        mappings:
          identifier: .key + "-" + .__projectKey + "-" + .__environmentKey
          title: .name
          blueprint: '"launchDarklySegment"'
          properties:
            name: .name
            description: .description
            creationDate: (.creationDate / 1000 | strftime("%Y-%m-%dT%H:%M:%SZ")) // null
            tags: .tags
            included: .included
            excluded: .excluded
            rules: .rules
            archived: .archived
          relations:
            project: .__projectKey
            environment: .__environmentKey + "-" + .__projectKey
  - kind: flag
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .key + "-" + .__projectKey
          title: .name
          blueprint: '"launchDarklyFeatureFlag"'
          properties:
            kind: .kind
            description: .description
            creationDate: .creationDate / 1000 | strftime("%Y-%m-%dT%H:%M:%SZ")
            clientSideAvailability: .clientSideAvailability
            temporary: .temporary
            tags: .tags
            maintainer: ._maintainer.email
            deprecated: .deprecated
            variations: .variations
            customProperties: .customProperties
            archived: .archived
            targets: .targets
            rules: .rules
          relations:
            project: .__projectKey
  - kind: environment
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .key + "-" + .__projectKey
          title: .name
          blueprint: '"launchDarklyEnvironment"'
          properties:
            defaultTtl: .defaultTtl
            secureMode: .secureMode
            defaultTrackEvents: .defaultTrackEvents
            requireComments: .requireComments
            confirmChanges: .confirmChanges
            tags: .tags
            critical: .critical
          relations:
            project: .__projectKey
  - kind: flag-status
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: >-
            . as $root | ._links.self.href | split("/") | last as $last |
            "\($last)-\($root.__environmentKey)"
          title: >-
            . as $root | ._links.self.href | split("/") | last as $last |
            "\($last)-\($root.__environmentKey)"
          blueprint: '"launchDarklyFFInEnvironment"'
          properties:
            status: .name
          relations:
            environment: .__environmentKey + "-" + .__projectKey
            featureFlag: . as $input | $input._links.self.href | split("/") | .[-1] + "-" + $input.__projectKey
