resources:
  - kind: sailpoint-example-kind
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .my_custom_id
          title: '(.my_component + " @ " + .my_service)'
          blueprint: '"sailpointExampleBlueprint"'
          properties:
            status: .my_enum
            text: .my_custom_text
            component: .my_component
            service: .my_service
            score: .my_special_score
