resources:
  - kind: backstage-entity
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .metadata.name
          title: .metadata.title // .metadata.name
          blueprint: '"backstageEntity"'
          properties:
            name: .metadata.name
